# .nosana-ci.yml
nosana:
  description: Nosana Blank Template

global:
  image: alpine:latest

  trigger:
    branch:
      - "*"

jobs:
  - name: Create README
    commands:
      - echo NOSANA_NODE
      
  - name: test-secret-manager
    secrets:
      - SECRET_KEY
    commands:
      - env
      - echo test secret manager value $SECRET_KEY
