# .nosana-ci.yml
nosana:
  description: Nosana Blank Template

global:
  image: alpine:latest

  trigger:
    branch:
      - "*"

jobs:
  - name: Create README
    commands:
      - echo NOSANA_NODE
      
  - name: test-secret-manager
    secrets:
      - SECRET_KEY
    commands:
      - env
      - echo test secret manager value 4f00d8ad-2ddf-4693-ad48-f8e754aa3f3c_test-secret
      