# .nosana-ci.yml
nosana:
  description: Nosana Blank Template

global:
  image: alpine:latest

  trigger:
    branch:
      - "*"
    secrets:
      - test-secret

jobs:
  - name: Create README
    commands:
      - echo NOSANA_NODE
      
  - name: test-secret-manager

    commands:
      - env
      - echo test secret manager value $test-secret
      